import SwiftUI

struct LegalDisclaimerView: View {
    @State private var disclaimerAccepted = false
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    Text("Legal Disclaimer")
                        .font(.title)
                        .padding()
                    
                    Text("""
                        1. No Medical Advice
                        The Breast Cancer Navigator app (hereinafter referred to as "the App") is designed to assist in the provision of information related to breast cancer treatment options. The information provided by the App, including recommendations generated by the algorithm, is for informational purposes only and is not intended to replace professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health providers with any questions you may have regarding a medical condition.
                        
                        2. No Doctor-Patient Relationship
                        The use of the App does not create a doctor-patient relationship. The information provided by the App should not be interpreted as specific medical advice or a recommendation for treatment. Users should not disregard or delay seeking professional medical advice based on information obtained through the App.
                        
                        3. Accuracy and Reliability
                        While efforts have been made to ensure the accuracy and reliability of the information provided by the App, [BCN Programers] (hereinafter referred to as "the Company") makes no representations or warranties, express or implied, regarding the completeness, accuracy, reliability, suitability, or availability of the App or the information, products, services, or related graphics contained in the App for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
                        
                        4. Limitation of Liability
                        To the fullest extent permitted by applicable law, the Company, its directors, officers, employees, agents, affiliates, and suppliers shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, or any damages whatsoever, including but not limited to, damages for loss of use, data, or profits, arising out of or in any way connected with the use or performance of the App, the delay or inability to use the App, the provision of or failure to provide services, or for any information, software, products, services, and related graphics obtained through the App, or otherwise arising out of the use of the App, whether based on contract, tort, negligence, strict liability or otherwise, even if the Company has been advised of the possibility of damages.
                        
                        5. No Guarantee
                        The Company does not guarantee that the App will always be available, uninterrupted, secure, or error-free. The Company disclaims any liability for any loss, injury, claim, liability, or damage of any kind resulting from, arising out of, or in any way related to your use of the App.
                        
                        6. Third-Party Content
                        The App may include links to third-party websites or content. The Company is not responsible for the content, accuracy, or opinions expressed in such third-party websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by the Company. Inclusion of any linked website does not imply approval or endorsement of the linked website by the Company. If you decide to leave the App and access these third-party websites, you do so at your own risk.
                        
                        7. Changes to Disclaimer
                        The Company reserves the right to modify this Legal Disclaimer at any time. Any changes will be posted on this page and your continued use of the App after such changes have been posted will constitute your agreement to such changes.
                        
                        8. Governing Law
                        This Legal Disclaimer shall be governed by and construed in accordance with the laws of Orlando, Florida, without regard to its conflict of law provisions. Any dispute arising under or in connection with this Legal Disclaimer shall be resolved exclusively in the courts located in Orlando, Florida.
                        """)
                        .padding()
                    
                    NavigationLink(destination: WelcomeView(), isActive: $disclaimerAccepted) {
                        Text("Accept")
                            .foregroundColor(.white)
                            .padding()
                            .frame(maxWidth: .infinity)
                            .background(Color.blue)
                            .cornerRadius(10)
                            .padding(.horizontal)
                    }
                    .opacity(disclaimerAccepted ? 0 : 1)
                    .animation(.easeInOut)
                }
                .padding()
            }
            .navigationBarTitle("Legal Disclaimer", displayMode: .inline)
        }
    }
}

struct LegalDisclaimerView_Previews: PreviewProvider {
    static var previews: some View {
        LegalDisclaimerView()
    }
}

